title: CPP Farm Store Group Project Assignments
description: IBM 6300 CPP Farm Store consulting project assignment hub.
baseurl: "/cpp-farm-store-theme"
url: "https://mjshawell.github.io"

markdown: kramdown
theme: null
